language: go
sudo: false
os:
  - linux
arch: 
  - arm64
dist: Bionic
go:
  - "1.16"
script:
    - go test -v .
    - cd cli/brook && mkdir out && go get -t -v . && go build -ldflags="-w -s" -o out/brook_linux_arm64 .
deploy:
  provider: releases
  api_key: ${GIT_TOKEN}
  file: 
    - out/brook_linux_arm64
  skip_cleanup: true
  on:
    all_branches: true
    branch: master
