language: go
sudo: false
os:
  - linux
arch: arm64
go:
  - "1.16"
script:
    - go test -v .
    - cd cli/brook && go get -t -v . && go build .
deploy:
  provider: releases
  api_key: ${GIT_TOKEN}
  file: 
    - brook
  skip_cleanup: true
  on:
    all_branches: true
    branch: master
